### ISSUE TITLE
while importing pysatml on python console it is showing error

### ISSUE THREAD

**Issue by prativadas** [adrianalbert/pysatml#2]
(base) C:\Users\Prativa>pip install pysatml
Requirement already satisfied: pysatml in c:\anaconda3\lib\site-packages (0.1.2)

(base) C:\Users\Prativa>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysatml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\anaconda3\lib\site-packages\pysatml\__init__.py", line 1, in <module>
    from satimage import SatImage
ModuleNotFoundError: No module named 'satimage'

**Comment by Ritvik29** [comment]
I think the code runs in python 2.7.  Try running it in python 2.7

**Comment by prativadas** [comment]
Thank you for your suggestion it works for me
